import { FontPreset } from '@/types';

export const FONT_PRESETS: Record<string, FontPreset> = {
  montserrat: {
    id: 'montserrat',
    name: 'Montserrat Bold',
    fontFamily: 'Montserrat',
    fileName: 'Montserrat-Bold.ttf',
    size: 90,
    bold: true,
    outline: 4,
    marginV: 0,
  },
  poppins: {
    id: 'poppins',
    name: 'Poppins SemiBold',
    fontFamily: 'Poppins',
    fileName: 'Poppins-SemiBold.ttf',
    size: 85,
    bold: false,
    outline: 3,
    marginV: 0,
  },
  bebas: {
    id: 'bebas',
    name: 'Bebas Neue',
    fontFamily: 'Bebas Neue',
    fileName: 'BebasNeue-Regular.ttf',
    size: 100,
    bold: false,
    outline: 5,
    marginV: 0,
  },
  oswald: {
    id: 'oswald',
    name: 'Oswald Bold',
    fontFamily: 'Oswald',
    fileName: 'Oswald-Bold.ttf',
    size: 88,
    bold: true,
    outline: 4,
    marginV: 0,
  },
  raleway: {
    id: 'raleway',
    name: 'Raleway Bold',
    fontFamily: 'Raleway',
    fileName: 'Raleway-Bold.ttf',
    size: 85,
    bold: true,
    outline: 3,
    marginV: 0,
  },
  anton: {
    id: 'anton',
    name: 'Anton',
    fontFamily: 'Anton',
    fileName: 'Anton-Regular.ttf',
    size: 95,
    bold: false,
    outline: 4,
    marginV: 0,
  },
  righteous: {
    id: 'righteous',
    name: 'Righteous',
    fontFamily: 'Righteous',
    fileName: 'Righteous-Regular.ttf',
    size: 88,
    bold: false,
    outline: 4,
    marginV: 0,
  },
  marker: {
    id: 'marker',
    name: 'Permanent Marker',
    fontFamily: 'Permanent Marker',
    fileName: 'PermanentMarker-Regular.ttf',
    size: 82,
    bold: false,
    outline: 4,
    marginV: 0,
  },
};

export const DEFAULT_FONT_PRESET = 'montserrat';
